spring.application.name=Session12

# Cấu hình thymelef

# tiền tố
spring.thymeleaf.prefix=classpath:/templates/
#hậu tố
spring.thymeleaf.suffix=.html
# cso lưu trũ tạm thời hay ko
spring.thymeleaf.cache=false

server.port=2006
